spring.application.name=finance
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/Finance
spring.datasource.username=postgres
spring.datasource.password=2006

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MGo4NqogMknImRe2qUfZ5IphvwRYe8awh+IuqxJaD6JitvQGWJ2nvTFewZs3OcsKvP9aBeVtD+XJx7LPdJU3UQ==
jwt.expiration=1800000 //30minutes
